[package]
edition = "2021"
name = "torii-c"
version = "0.0.9"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dojo-types = { git = "https://github.com/dojoengine/dojo", rev = "b48657e804864068f7ca3803e41656b51d9a4921" }
torii-client = { git = "https://github.com/dojoengine/dojo", rev = "b48657e804864068f7ca3803e41656b51d9a4921"}
torii-grpc = { git = "https://github.com/dojoengine/dojo", features = [
    "client",
], rev = "b48657e804864068f7ca3803e41656b51d9a4921" }

parking_lot = "0.12.1"
starknet = "0.8.0"
starknet-crypto = "0.6.0"
tokio = { version = "1.32.0", default-features = false, features = ["rt"] }
url = "2.5.0"
tonic = "0.10.2"
anyhow = "1.0.76"
tokio-stream = "0.1.14"
serde = { version = "1.0.193", features = ["derive"] }
serde-wasm-bindgen = "0.6.0"
wasm-bindgen = "=0.2.89"
wasm-bindgen-futures = "0.4.37"

[build-dependencies]
cbindgen = "0.26.0"
