[package]
edition = "2021"
name = "torii-c"
version = "0.0.6"

[lib]
crate-type = ["cdylib"]

[dependencies]
dojo-types = { git = "https://github.com/dojoengine/dojo" }
torii-client = { git = "https://github.com/dojoengine/dojo" }
torii-grpc = { git = "https://github.com/dojoengine/dojo", features = [
    "client",
] }

parking_lot = "0.12.1"
starknet = "0.8.0"
starknet-crypto = "0.6.0"
tokio = { version = "1.32.0", features = [ "full" ] }
url = "2.5.0"
tonic = "0.10.2"
futures-util = "0.3.29"
futures-channel = "0.3.29"

[build-dependencies]
cbindgen = "0.24.0"
csbindgen = "1.8.3"
